python run_search.py -p 1 -s 1 > p1_s1.txt
python run_search.py -p 1 -s 2 > p1_s2.txt
python run_search.py -p 1 -s 3 > p1_s3.txt
python run_search.py -p 1 -s 4 > p1_s4.txt
python run_search.py -p 1 -s 5 > p1_s5.txt
python run_search.py -p 2 -s 1 > p2_s1.txt
python run_search.py -p 2 -s 2 > p2_s2.txt
python run_search.py -p 2 -s 3 > p2_s3.txt
python run_search.py -p 2 -s 4 > p2_s4.txt
python run_search.py -p 2 -s 5 > p2_s5.txt
python run_search.py -p 3 -s 1 > p3_s1.txt
python run_search.py -p 3 -s 2 > p3_s2.txt
python run_search.py -p 3 -s 3 > p3_s3.txt
python run_search.py -p 3 -s 4 > p3_s4.txt
python run_search.py -p 3 -s 5 > p3_s5.txt